### ISSUE TITLE
TLS CLIENT ALERT: Fatal - Unknown CA

### ISSUE THREAD

**Issue by Sadique-The-Alchemist** [infinitered/elasticsearch-elixir#120]
`mix elasticsearch.build posts  --cluster Elastic.ElasticsearchCluster` responds 
** (Mix) Index posts could not be created.

    %HTTPoison.Error{reason: {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:2109 generated CLIENT ALERT: Fatal - Unknown CA\n'}}, id: nil}

**Comment by Sadique-The-Alchemist** [comment]
I installed Elastic Search through Docker and it's initial REST API call to ensure Elastic Search properly installed was
`curl --cacert http_ca.crt -u elastic:$ELASTIC_PASSWORD https://localhost:9200` .
The `mix elasticsearch.build` command does not support `--cacert` as option

**Comment by lovebes** [comment]
If you're using OTP26 - https://www.erlang.org/blog/otp-26-highlights/#ssl-safer-defaults
Try this in your config:

```
config :my_app, MyApp.Elasticsearch.Cluster,
  enabled: false,
  default_options: [
    ssl: [{:verify, :verify_none}] #<=== this line
  ],
  api: Elasticsearch.API.HTTP,
  json_library: Jason
```

I followed the [docker compose file setup for cluster](https://www.elastic.co/guide/en/elasticsearch/reference/8.11/docker.html#docker-compose-file), and this seems to work.
