### ISSUE TITLE
elasticsearch deprecated type=string 

### ISSUE THREAD

**Issue by steffkes** [infinitered/elasticsearch-elixir#14]
The doc blocks for [`Index.create_from_file/2`](https://github.com/infinitered/elasticsearch-elixir/blob/ce904e5dea959a5caefe2cde15669bba43ac3fa6/lib/elasticsearch/indexing/index.ex#L229) include a sample mapping for elasticsearch where it uses `type=string` .. which fails on recent versions, [since it got deprecated almost two years ago in 5.x](https://www.elastic.co/blog/strings-are-dead-long-live-strings):

> With the release of Elasticsearch 5.0 coming closer, it is time to introduce one of the release highlights of this upcoming release: the removal of the string type. 

[since 5.1.1 is explicitly referenced in `bin/setup`](https://github.com/infinitered/elasticsearch-elixir/blob/ce904e5dea959a5caefe2cde15669bba43ac3fa6/bin/setup#L34) i'm hesitating to "just change" `type=string` to `type=text` in the doc block, which works in 6.2.3 w/o actually upgrading the `setup` script as well .. 

WDYT @danielberkompas ?

**Comment by danielberkompas** [comment]
The `text` type is supported on 5.1.1, so I'll just change the sample mapping.
