### ISSUE TITLE
Compilation error in file lib/mix/elasticsearch.build.ex

### ISSUE THREAD

**Issue by travcunn** [infinitered/elasticsearch-elixir#30]
When compiling my Elixir (1.6.5) project with elasticsearch-elixir installed, I run into this error:

```
Compiling 15 files (.ex)

== Compilation error in file lib/mix/elasticsearch.build.ex ==
** (CompileError) lib/mix/elasticsearch.build.ex:92: undefined function maybe/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
could not compile dependency :elasticsearch, "mix compile" failed. You can recompile this dependency with "mix deps.compile elasticsearch", update it with "mix deps.update elasticsearch" or clean it with "mix deps.clean elasticsearch"
```

Also I love this project!!!!

**Comment by rhnonose** [comment]
@travcunn which version are you using?

I recompiled the `0.4.0` version with elixir `1.6.5` and it compiled just fine.

**Comment by travcunn** [comment]
Whoops simple error. I was using 0.4.0 but forgot to install all proper dependencies (Maybe was the one that wasn't installed). Thanks for the quick reply - I need more coffee.
