### ISSUE TITLE
Error installing on ubuntu linux

### ISSUE THREAD

**Issue by g13ydson** [infinitered/elasticsearch-elixir#46]
I'm trying to install on Ubuntu 18, but this bug is appearing when installing Kibana. Elasticsearch is installed successfully.

`mix elasticsearch.install . --version 6.2.4
`

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 27.7M  100 27.7M    0     0  1392k      0  0:00:20  0:00:20 --:--:-- 1976k

`** (Mix) Unsupported system for Kibana: {:unix, :linux}
`

**Comment by danielberkompas** [comment]
@g13ydson See these lines:

https://github.com/infinitered/elasticsearch-elixir/blob/3ab2ca4e13bb2e7fdf4e144951753f4e340dce11/lib/mix/elasticsearch.install.ex#L45-L51

We might possibly be able to fix this by adding a `{:unix, :linux}` clause to the case statement, returning "kibana-#{version}-linux-x86_64". It just depends on where Elasticsearch hosts the Kibana tar for Linux.

I don't have access to a Linux machine at the moment. Could you try making this change and see if it works?

**Comment by g13ydson** [comment]
Yes, you're right @danielberkompas . I added the case statement and it worked perfectly. I created a pull request with the fix. Thank you.

**Comment by danielberkompas** [comment]
I released a new version with this change: `0.5.4`.
