### ISSUE TITLE
SSL Errors with HTTPoison

### ISSUE THREAD

**Issue by collegeimprovements** [infinitered/elasticsearch-elixir#5]
I'm getting the follwing error:
```elixir
$ Elasticsearch.get("/_cat/health")

13:51:37.261 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'certify', 32, 'at ssl_handshake.erl:1624 generated CLIENT ALERT: Fatal - Unknown CA', 10]
{:error, %HTTPoison.Error{id: nil, reason: {:tls_alert, 'unknown ca'}}}
```

When I run the following query, it runs successfully. [Ref](https://github.com/edgurgel/httpoison/blob/master/README.md#note-about-broken-ssl-in-erlang-19)
```elixir
$ HTTPoison.get("https://servername:9200/_cat/health", [], [ ssl: [{:versions, [:'tlsv1.2']}] ])
```

Can we set some `Env var` or set some `config value` to solve this issue ?
I tried the following in `config.exs` file with no good result.
```elixir
config :ssl, protocol_version: :"tlsv1.2"
```

**Comment by danielberkompas** [comment]
@collegeimprovements What version of Elasticsearch are you running?

**Comment by collegeimprovements** [comment]
We are on `Elasticsearch-5.5`.

**Comment by danielberkompas** [comment]
This error occurs when the certificate authority for the target url is unknown to Hackney. Is it a self-signed certificate?

See these other GitHub issues for reference:

https://github.com/edgurgel/httpoison/issues/62
https://github.com/edgurgel/httpoison/issues/119
https://github.com/edgurgel/httpoison/issues/294

**Comment by collegeimprovements** [comment]
Yes. It seems like we have self signed certificates. Is there any workaround for this issue ?
[ e.g. we are able to hit `HTTPoison` queries with the above mentioned `ssl option`. ]
Or there is no simple workaround apart from asking people who host ElasticSearch to provide certificate files!?

**Comment by danielberkompas** [comment]
We should add an `hackney_options` configuration setting to `Elasticsearch`. This would allow you to pass the `ssl: [{:versions, [:'tlsv1.2']}]` settings that are working for you.
