### ISSUE TITLE
bulk_wait_interval is unused

### ISSUE THREAD

**Issue by rosswilson** [infinitered/elasticsearch-elixir#7]
I can't see any reference to where `bulk_wait_interval` is being used. Is there a planned future use of it? If not, would you accept a PR to update the README?

**Comment by danielberkompas** [comment]
Yes, we plan to make it work as described in the README.

**Comment by danielberkompas** [comment]
This has been fixed. https://github.com/infinitered/elasticsearch-elixir/commit/81fa49bb787eefe6ce6113dd67dd2fe9f6f8b3b7
